# Performance profiler (paired line at end of file)
# zmodload zsh/zprof

# rather than "~/Library/Application\ Support/"
export XDG_CONFIG_HOME="$HOME/.config"

# Ensure user-installed thirdparty tools are in path
export PATH="/usr/local/bin:$PATH"

# Disable printing of what is updated on brew servers
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_UPDATE_REPORT_NEW=1

# User scripts
export PATH="$HOME/dotfiles/scripts/:$PATH"

# Override builtin binaries with GNU ones installed via homebrew
export PATH="$HOMEBREW_PREFIX/opt/grep/libexec/gnubin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/gawk/libexec/gnubin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/unzip/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/gzip/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/bc/bin:$PATH"
# export PATH="$HOMEBREW_PREFIX/opt/ccache/libexec:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/curl/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
export LIBGCCJIT_LIBRARY_PATH="$HOMEBREW_PREFIX/opt/libgccjit/lib"

# export LIBCLANG_PATH="$HOMEBREW_PREFIX/opt/llvm@14/lib"
# export PATH="$HOMEBREW_PREFIX/opt/llvm@14/bin:$PATH"

#Ensure binary packages for languages are in path
export PATH="$HOMEBREW_PREFIX/opt/rustup/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export DYLD_LIBRARY_PATH="$HOMEBREW_PREFIX/lib:$DYLD_LIBRARY_PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:$HOME/.lmstudio/bin"
# End of LM Studio CLI section

# For openblas
export LDFLAGS="-L$HOMEBREW_PREFIX/opt/openblas/lib"
export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/openblas/include"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openblas/lib/pkgconfig"

# For curl (from brew instructions)
export LDFLAGS="$LDFLAGS -L$HOMEBREW_PREFIX/opt/curl/lib"
export CPPFLAGS="$CPPFLAGS -I$HOMEBREW_PREFIX/opt/curl/include"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/curl/lib/pkgconfig:$PKG_CONFIG_PATH"

# For clang
# export LDFLAGS="-L/opt/homebrew/opt/llvm@14/lib $LDFLAGS"
# export CPPFLAGS="-I/opt/homebrew/opt/llvm@14/include $CPPFLAGS"

# https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
if type brew &>/dev/null; then
    _brew_prefix="$(brew --prefix)"
    FPATH="$_brew_prefix/share/zsh/site-functions:${FPATH}"

    zstyle ':completion:*' rehash true
    zstyle ':completion:*' use-cache on
    zstyle ':completion:*' cache-path ~/.zsh/cache
    autoload -Uz compinit
    compinit -C
    # https://stackoverflow.com/questions/29196718/zsh-highlight-on-tab
    zstyle ':completion:*' menu select
fi

# Custom LS/Eza colors (cached for performance, regenerated by set-theme.sh)
_theme_mode="dark"
[[ -f "$HOME/.local/state/theme-mode" ]] && _theme_mode="$(cat "$HOME/.local/state/theme-mode")"

_vivid_cache="$HOME/.cache/vivid-ls-colors"
if [[ ! -f "$_vivid_cache" ]]; then
    mkdir -p "$(dirname "$_vivid_cache")"
    local _vivid_flavor="catppuccin-mocha"
    [[ "$_theme_mode" == "light" ]] && _vivid_flavor="catppuccin-latte"
    vivid generate "$_vivid_flavor" >"$_vivid_cache"
fi
export LS_COLORS="$(cat "$_vivid_cache")"

export PATH="$HOME/.local/bin:$PATH"

# Aliases
alias sz='source $HOME/.zshrc'
alias ls='eza -l --color=always --icons --header --classify --group-directories-first'
alias la='eza -al --color=always --icons --header --classify --group-directories-first'
alias tree="eza --tree --icons -a --group-directories-last -I '.git|node_modules|.pixi|.venv|.databricks|.ruff_cache'"
alias cp='cp -i'                         # confirm before overwriting
alias df='df -h'                         # human readable sizes
alias free='free -m'                     # sizes in MB
alias cloc='tokei --hidden --sort code --num-format commas' # fast CLOC implementation with nice defaults
alias ee="yazi"
alias gg="lazygit"
alias g="git"
alias p="pixi"
alias codi="codium"
alias oc="opencode"
alias cl="claude"
alias tgpt='tgpt -i -m --preprompt "Be specific and brief. Avoid detailed explanations unless specifically asked."'
alias tmux_sesh_info='tmux display -p -F "#{session_name}:#{window_index}.#{pane_index}  #{pane_current_command}  #{pane_current_path}"'
alias glow="glow -p -w 200"
alias glows="glow -p -w 150"
mdopen() {
    pandoc "$1" -o /tmp/mdpreview.html \
        --standalone \
        --css ~/.config/pandoc/github-dark.css \
        --syntax-highlighting=idiomatic &&
        open /tmp/mdpreview.html
}

export CLIPBOARD_THEME=ansi

clip() {
    if [ $# -lt 1 ]; then
        echo "Usage: clip <file> [more files...]"
        echo "Copies file(s) to macOS clipboard as file reference(s) (for pasting into apps/Finder)."
        return 1
    fi

    # Ensure we're on macOS with osascript available
    if ! command -v osascript >/dev/null 2>&1; then
        echo "Error: osascript not found. This command only works on macOS."
        return 1
    fi

    local as_items=""
    local count=0
    local file abs escaped

    for file in "$@"; do
        if [ ! -e "$file" ]; then
            echo "Error: '$file' does not exist."
            return 1
        fi
        abs="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"

        # Escape for AppleScript string literal
        escaped="${abs//\\/\\\\}"
        escaped="${escaped//\"/\\\"}"

        if [ -n "$as_items" ]; then
            as_items="$as_items, (POSIX file \"$escaped\") as alias"
        else
            as_items="(POSIX file \"$escaped\") as alias"
        fi
        count=$((count + 1))
    done

    if [ $count -eq 1 ]; then
        osascript >/dev/null <<EOF
set the clipboard to $as_items
EOF
    else
        osascript >/dev/null <<EOF
set the clipboard to { $as_items }
EOF
    fi

    echo "📦 $count item(s) placed on the clipboard as file reference(s). Try Cmd+V in Finder or apps that accept file paste."
}

# Use y instead of yazi to start, and press q to quit, you'll see the CWD changed.
# Sometimes, you don't want to change, press Q to quit.
function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

# Faster NVM
eval "$(fnm env --use-on-cd --shell zsh)"

# # Use ;; as the trigger sequence instead of the default **
export FZF_COMPLETION_TRIGGER=';;'
# FZF Catppuccin colors (sourced from theme file)
source "$HOME/dotfiles/scripts/themes/fzf-${_theme_mode:-dark}.sh"
# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
--walker-skip .git,node_modules,target
--preview 'bat -n --color=always {}'
--bind 'ctrl-/:change-preview-window(down|hidden|)' --border"
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
--bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
--color header:italic
--header 'Press CTRL-Y to copy command into clipboard' --border --reverse"
# Print tree structure in the preview window
export FZF_ALT_C_OPTS="
--walker-skip .git,node_modules,target
--preview 'tree -C {}' --border"

# bat can be used as a colorizing pager for man
# export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"
export MANPAGER="nvim +Man!"

# bat can overtake `--help` flags
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain --paging=never'
alias -g -- --help='--help 2>&1 | bat --language=help --style=plain --paging=never'
alias bag="batgrep --paging=never --context=0"

# enable mouse scroll in pager
export LESS="-R --mouse"

# Tealdeer (tldr)
export TEALDEER_CONFIG_DIR="$HOME/.config/tealdeer"
# cp completion/zsh_tealdeer /usr/share/zsh/site-functions/_tldr

# Startup header
# fastfetch --logo macos
# pokeget random --hide-name | fastfetch --file-raw -

# ART=(
#     ""
#     ".·:'''''''''''''''''''':·."
#     ": :                    : :"
#     ": :  ██████╗ ██████╗   : :"
#     ": :  ██╔══██╗██╔══██╗  : :"
#     ": :  ██████╔╝██████╔╝  : :"
#     ": :  ██╔══██╗██╔══██╗  : :"
#     ": :  ██║  ██║██║  ██║  : :"
#     ": :  ╚═╝  ╚═╝╚═╝  ╚═╝  : :"
#     ": :                    : :"
#     "'·:....................:·'"
# )
# printf "%s\n" "${ART[@]}" | fastfetch --file-raw -

if [[ "$_theme_mode" == "light" ]]; then
  CLR_BORDER="\033[38;2;114;135;253m"
  CLR_CONTENTS="\033[38;2;30;102;245m"
else
  CLR_BORDER="\033[38;2;180;190;254m"
  CLR_CONTENTS="\033[38;2;137;180;250m"
fi
CLR_RESET="\033[0m"

# ASCII Art with embedded ANSI codes
ART=(
    ""
    "${CLR_BORDER}.·:'''''''''''''''''''':·.${CLR_RESET}"
    "${CLR_BORDER}: :${CLR_RESET}                    ${CLR_BORDER}: :${CLR_RESET}"
    "${CLR_BORDER}: :  ${CLR_CONTENTS}██████╗ ██████╗${CLR_BORDER}   : :${CLR_RESET}"
    "${CLR_BORDER}: :  ${CLR_CONTENTS}██╔══██╗██╔══██╗${CLR_BORDER}  : :${CLR_RESET}"
    "${CLR_BORDER}: :  ${CLR_CONTENTS}██████╔╝██████╔╝${CLR_BORDER}  : :${CLR_RESET}"
    "${CLR_BORDER}: :  ${CLR_CONTENTS}██╔══██╗██╔══██╗${CLR_BORDER}  : :${CLR_RESET}"
    "${CLR_BORDER}: :  ${CLR_CONTENTS}██║  ██║██║  ██║${CLR_BORDER}  : :${CLR_RESET}"
    "${CLR_BORDER}: :  ${CLR_CONTENTS}╚═╝  ╚═╝╚═╝  ╚═╝${CLR_BORDER}  : :${CLR_RESET}"
    "${CLR_BORDER}: :${CLR_RESET}                    ${CLR_BORDER}: :${CLR_RESET}"
    "${CLR_BORDER}'·:....................:·'${CLR_RESET}"
)
oneline=$(
    IFS=$'\n'
    echo "${ART[*]}"
)
echo "$oneline" | fastfetch --file-raw -

# Zoxide completions, cache etc
eval "$(zoxide init zsh --cmd cd)"

# Setup ZSH plugins
source "$HOME"/.config/fsh/fast-syntax-highlighting.plugin.zsh
source "$_brew_prefix"/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source "$HOME/.config/fzf-tab/fzf-tab.plugin.zsh"

# API keys and secrets
_load_secret() { [[ -f "$1" ]] && cat "$1" || echo ""; }
export OPENAI_API_KEY=$(_load_secret "$HOME"/dotfiles/Secrets/openai_api_key)
export OPENAI_API_KEY_PRO=$(_load_secret "$HOME"/dotfiles/Secrets/openai_api_key_pro)
export GOOGLE_API_KEY=$(_load_secret "$HOME"/dotfiles/Secrets/google_api_key)
export ANTHROPIC_API_KEY=$(_load_secret "$HOME"/dotfiles/Secrets/anthropic_api_key)
export DEEPSEEK_API_KEY=$(_load_secret "$HOME"/dotfiles/Secrets/deepseek_api_key)
export BACKBLAZE_API_KEY=$(_load_secret "$HOME"/dotfiles/Secrets/backblaze_api_key)

# Matplotlib config directory
export MPLCONFIGDIR=$HOME/.matplotlib

# Local Neovim
export PATH="$HOME/Documents/Programming/ThirdParty/neovim/build/bin:$PATH"
export EDITOR=nvim
export MASON_BIN_PATH="$HOME/.local/share/nvim/mason/bin"

# Local Odin
export PATH="$HOME/tools/odin-macos-arm64:$PATH"

# Pixi completions
eval "$(pixi completion --shell zsh)"
export PATH="$HOME/.pixi/bin:$PATH"

# Android SDK
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# ZSH vi mode
ZVM_VI_YANK_CLIP=1
ZVM_VI_PUT_CLIP=1
ZVM_INIT_MODE=sourcing
source "$_brew_prefix"/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# NOTE: Need to re-apply keybind customizations, to ensure these are available in Insert mode
# The plugin will auto execute this zvm_after_init function
zvm_after_init() {
    # Set up fzf key bindings and fuzzy completion
    source <(fzf --zsh)
}

# Setup starship prompt (MUST be after zsh-vi-mode to avoid recursive zle-keymap-select)
eval "$(starship init zsh)"

# Longer shell history
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=1000000000
export SAVEHIST=1000000000
setopt EXTENDED_HISTORY

# Start tmux properly
function tt() {
    if command -v tmux &>/dev/null && command -v sesh &>/dev/null && [ -z "$TMUX" ]; then
        TMUX_DEFAULT_SESSION="main"
        # Check if the session already exists
        if tmux has-session -t "$TMUX_DEFAULT_SESSION" 2>/dev/null; then
            # Attach to existing session
            tmux attach-session -t "$TMUX_DEFAULT_SESSION"
        else
            # Create new session with sesh
            sesh connect "$TMUX_DEFAULT_SESSION" || tmux new-session -s "$TMUX_DEFAULT_SESSION"
        fi
    fi
}

# Performance profiler (paired line at start of file)
# zprof
