" ---------- CORE START -------------------------------------------------------

" Don't try to be vi compatible
set nocompatible

" Enable syntax highlighting
syntax on

" Set leader key
let mapleader = " "

let &t_SI = "\e[5 q"  " IBeam for Insert mode
let &t_SR = "\e[4 q"  " Underline for Replace mode
let &t_EI = "\e[2 q"  " Block for Normal mode
" Set the cursor to block (Normal mode) on Vim startup
autocmd VimEnter * silent! exe "normal \e[2 q"

" Disable swap files
set noswapfile
set noundofile

" Line numbers and cursor settings
set number
set relativenumber
set termguicolors
set signcolumn=yes
set cursorline
set mouse=a

" Show mode and command
set noshowmode
set noshowcmd
set cmdheight=1

" Minimal number of screen lines to keep above and below the cursor
set scrolloff=10

" Indentation settings
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

" Disable line wrapping
set nowrap

" Configure backspace behavior
set backspace=indent,eol,start

" Search settings
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

" Enable break indent
set breakindent

" Save undo history
set undofile

" Decrease mapped sequence wait time
set timeoutlen=300

" Configure how new splits should be opened
set splitright
set splitbelow

" Update time for CursorHold autocmds
set updatetime=250

" Clipboard integration (Vim doesn't support Lua's `vim.schedule`)
set clipboard=unnamedplus

" ---------- CORE END ---------------------------------------------------------

" ---------- PLUGINS START ----------------------------------------------------
call plug#begin()

" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'svermeulen/vim-subversive'
Plug 'machakann/vim-highlightedyank'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'vim-airline/vim-airline'

call plug#end()

colorscheme catppuccin_mocha
let g:airline_powerline_fonts = 1
let g:airline_theme = 'catppuccin_mocha'
let g:highlightedyank_highlight_duration = 80
" ---------- PLUGINS END ------------------------------------------------------

" ---------- KEYMAPS START ----------------------------------------------------
nnoremap <silent> <Esc> :nohlsearch<CR>
" Replace `x` with black hole register version
nnoremap <silent> x "_x

" Window navigation mappings
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k

" BUG: Does not work :(
" Maps Alt-J and Alt-K to macros for moving lines up and down
" Works for modes: Normal, Insert and Visual
nnoremap ∆ :m .+1<CR>==
nnoremap ˚ :m .-2<CR>==
inoremap ∆ <Esc>:m .+1<CR>==gi
inoremap ˚ <Esc>:m .-2<CR>==gi
vnoremap ∆ :m '>+1<CR>gv=gv
vnoremap ˚ :m '<-2<CR>gv=gv

" Buffer/tab navigation
nnoremap [t :bprevious<CR>
nnoremap ]t :bnext<CR>

" Center cursor while scrolling or navigating
nnoremap <silent> <C-u> <C-u>zz
nnoremap <silent> <C-d> <C-d>zz
nnoremap <silent> G Gzz

" Redo
nnoremap <silent> U :redo<CR>

" Yank to the system clipboard with 'y'
nnoremap y "+y
vnoremap y "+y
inoremap <C-y> "+y

" Paste from the system clipboard with 'p'
nnoremap p "+p
vnoremap p "+p
inoremap <C-p> "+p

" Paste in next line
nnoremap <silent> <C-p> o<ESC>"+p

" s for substitute
nmap s <plug>(SubversiveSubstitute)
nmap ss <plug>(SubversiveSubstituteLine)
nmap S <plug>(SubversiveSubstituteToEndOfLine)
" ---------- KEYMAPS END ------------------------------------------------------

