[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim -c \":FzfLua files\""

[[session]]
name = "Obsidian Main Vault"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Obsidian Main"


[[session]]
name = "Spotify Music"
path = "~/"
startup_command = "spotify_player"
