# Close input by once Esc press
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

# Smart enter: enter for directory, open for file
[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# Copy selected files to the system clipboard while yanking
[[manager.prepend_keymap]]
on = "y"
run = ['''
	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank"]

# Maximize preview pane
[[manager.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

# File navigation wraparound
# [[manager.prepend_keymap]]
# on = "k"
# run = "plugin arrow --args=-1"
#
# [[manager.prepend_keymap]]
# on = "j"
# run = "plugin arrow --args=1"
#
# [[manager.prepend_keymap]]
# on = "<Up>"
# run = "plugin arrow --args=-1"
#
# [[manager.prepend_keymap]]
# on = "<Down>"
# run = "plugin arrow --args=1"

# vim style -to-char
[[manager.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<z>"
run = "plugin fzf"
desc = "Start FZF"

[[manager.prepend_keymap]]
on = ["c", "g"]
run = '''
	shell 'realpath --relative-to="$(git rev-parse --show-toplevel)" "$@" | pbcopy'
'''
desc = "Copy file/directory path from git repo root"

[[manager.prepend_keymap]]
on = "E"
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[manager.prepend_keymap]]
on = "-"
run = "plugin eza-preview --args='--inc-level'"
desc = "Increment tree level"

[[manager.prepend_keymap]]
on = "_"
run = "plugin eza-preview --args='--dec-level'"
desc = "Decrement tree level"

[[manager.prepend_keymap]]
on = [".", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"

# TODO: fix hidden toggle to <.h>
# TODO: fix Z that uses fzf for directory navigation - limit depth AND start from ~ always
# TODO: set z to use same ^ fzf but start from current directory
# TODO: Set keymap <c-o> to back and <c-i> to forward
# TODO: Set keymap <c-p> to show 'properties'/'info' (default is <c-i>)
# TODO: Set Q keymap to quit yazi and navigate shell to directory that yazi was in
