# Close input by once Esc press
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

# Copy selected files to the system clipboard while yanking
[[mgr.prepend_keymap]]
on = "y"
run = ['''
	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank"]

# File navigation wraparound
# [[manager.prepend_keymap]]
# on = "k"
# run = "plugin arrow --args=-1"
#
# [[manager.prepend_keymap]]
# on = "j"
# run = "plugin arrow --args=1"
#
# [[manager.prepend_keymap]]
# on = "<Up>"
# run = "plugin arrow --args=-1"
#
# [[manager.prepend_keymap]]
# on = "<Down>"
# run = "plugin arrow --args=1"

# vim style -to-char
[[mgr.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "Zoxide jump"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"
desc = "FZF directory jump"

[[mgr.prepend_keymap]]
on = "<C-o>"
run = "back"
desc = "Go back"

[[mgr.prepend_keymap]]
on = "<C-i>"
run = "forward"
desc = "Go forward"

[[mgr.prepend_keymap]]
on = ["c", "g"]
run = '''
	shell 'realpath --relative-to="$(git rev-parse --show-toplevel)" "$@" | pbcopy'
'''
desc = "Copy file/directory path from git repo root"

[[mgr.prepend_keymap]]
on = ["c", "h"]
run = '''
	shell 'realpath "$@" | sed "s|^$HOME|~|" | pbcopy'
'''
desc = "Copy file/directory path from home"

[[mgr.prepend_keymap]]
on = "E"
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom-toggle"
desc = "Toggle fullscreen preview"

[[mgr.prepend_keymap]]
on = [".", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"


[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]
desc = "Copy selection to system clipboard"

# Utils group
[[mgr.prepend_keymap]]
on = ["u", "s"]
run = "plugin toggle-status"
desc = "Toggle status bar"

[[mgr.prepend_keymap]]
on = ["u", "h"]
run = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on = ["u", "d"]
run = "plugin diff"
desc = "Diff selected file with hovered"

[[mgr.prepend_keymap]]
on = ["u", "e"]
run = "plugin exif-preview"
desc = "Show EXIF metadata"

[[mgr.prepend_keymap]]
on = ["u", "t"]
run = "plugin eza-preview"
desc = "Toggle flat/tree dir preview"

# Permissions group
[[mgr.prepend_keymap]]
on = ["p", "p"]
run = "plugin chmod"
desc = "Chmod (interactive)"

[[mgr.prepend_keymap]]
on = ["p", "r"]
run = "shell 'chmod u+r \"$@\"' --confirm"
desc = "Toggle +r (owner read)"

[[mgr.prepend_keymap]]
on = ["p", "w"]
run = "shell 'chmod u+w \"$@\"' --confirm"
desc = "Toggle +w (owner write)"

[[mgr.prepend_keymap]]
on = ["p", "x"]
run = "shell 'chmod u+x \"$@\"' --confirm"
desc = "Toggle +x (owner exec)"

[[mgr.prepend_keymap]]
on = ["p", "R"]
run = "shell 'chmod u-r \"$@\"' --confirm"
desc = "Toggle -r (owner read)"

[[mgr.prepend_keymap]]
on = ["p", "W"]
run = "shell 'chmod u-w \"$@\"' --confirm"
desc = "Toggle -w (owner write)"

[[mgr.prepend_keymap]]
on = ["p", "X"]
run = "shell 'chmod u-x \"$@\"' --confirm"
desc = "Toggle -x (owner exec)"

[[mgr.prepend_keymap]]
on = "<Tab>"
run = "forward"
desc = "Go forward"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "spot"
desc = "Spot hovered file"

