# Close input by once Esc press
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# Smart enter: enter for directory, open for file
[[manager.prepend_keymap]]
on   = "l"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

# Copy selected files to the system clipboard while yanking
[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank" ]

# Maximize preview pane
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

# File navigation wraparound
[[manager.prepend_keymap]]
on  = "k"
run = "plugin --sync arrow --args=-1"

[[manager.prepend_keymap]]
on  = "j"
run = "plugin --sync arrow --args=1"

# vim style -to-char
[[manager.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"
