# Close input by once Esc press
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

# Smart enter: enter for directory, open for file
[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# Copy selected files to the system clipboard while yanking
[[manager.prepend_keymap]]
on = "y"
run = ['''
	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank"]

# Maximize preview pane
[[manager.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"

# File navigation wraparound
[[manager.prepend_keymap]]
on = "k"
run = "plugin arrow --args=-1"

[[manager.prepend_keymap]]
on = "j"
run = "plugin arrow --args=1"

[[manager.prepend_keymap]]
on = "<Up>"
run = "plugin arrow --args=-1"

[[manager.prepend_keymap]]
on = "<Down>"
run = "plugin arrow --args=1"

# vim style -to-char
[[manager.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<z>"
run = "plugin fzf"
desc = "Start FZF"

[[manager.prepend_keymap]]
on = ["c", "g"]
run = '''
	shell 'realpath --relative-to="$(git rev-parse --show-toplevel)" "$@" | pbcopy'
'''
desc = "Copy file/directory path from git repo root"
