[mgr]
show_hidden = true

[preview]
image_delay = 100
max_width = 3000

[plugin]
prepend_previewers = [
  { name = "*/", run = "eza-preview" },
  # { name = "*.csv", run = "rich-preview"},
  { name = "*.md", run = "rich-preview" },
  { name = "*.ipynb", run = "rich-preview" },
  { name = "*.json", run = "rich-preview" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
