# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

format = '''
[╭─](bold green) $all
[╰](bold green)$character'''

# Inserts a blank line between shell prompts
add_newline = true

# Some language version commands were taking longer to fill prompt modules
command_timeout = 1000

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
# error_symbol = "[✖](bold red)"

# Controls line break between multi-line custom prompts
[line_break]
disabled = true

# Module overrides
[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[directory]
truncation_length = 4
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_status]
disabled = true

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = ' '

[os.symbols]
Macos = " "

[package]
disabled = true

[pixi]
symbol = " "

[python]
symbol = " "
style = "green"

[rust]
symbol = "󱘗 "

# Palette definitions
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
