line-length = 100
# Read more here https://beta.ruff.rs/docs/rules/
# By default, Ruff enables Flake8's E and F rules
# Pyflakes - F, pycodestyle - E, W
# flake8-builtins - A
# Pylint - PLC, PLE, PLW
# isort - I
[lint]
select = ['ALL']
ignore = [
    "E501",   # line too long
    "D100",   # missing docstring in public module
    "D101",   # missing docstring in class
    "D102",   # missing docstring in method
    "D103",   # missing docstring in function
    "TRY003", # long exception messages
    "EM101",  # exception message string literal
    "EM102",  # exception message fstring
    "RET504", # unnecessary assignment before return
    "RET505", # unnecessary else after return
    "FIX002", # remove TODO
    "TD002",  # missing author in TODO
    "TD003",  # missing issue link in TODO
    "PT018",  # break apart multi-case assertions
    "FA102",  # new syntax for annotations without __future__ import
]
